# Generated by Django 4.2.7 on 2023-11-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_biodata_created_at_biodata_nin_biodata_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodata',
            name='atm',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
    ]
